from flask_ask import Ask, statement, question
from flask import Flask

app = Flask(__name__)
ask = Ask(app, '/')

noun = ''
verb = ''
adjective = ''

@ask.launch
def welcome():
    msg = """Welcome to the Madlib Generator, give me a noun, an adjective,
    an adverb, and a verb and I will give you a madlib.
    To start please give me a noun."""

    return question(msg)

@ask.intent("NounIntent")
def noun_intent(Noun):
    legit =  checker(word=Noun, grammar='noun')

    if legit == False:
        return err('noun')

    global noun
    noun = Noun

    return question('Thanks for the noun, now I need an adjective.')

@ask.intent("AdjectiveIntent")
def adjective_intent(Adjective):
    legit =  checker(word=Adjective, grammar='adjective')

    if legit == False:
        return err('adjective')

    global adjective
    adjective = Adjective

    return question('Thanks for the adjective, now I need a verb.')

@ask.intent("VerbIntent")
def verb_intent(Verb):
    legit =  checker(word=Verb, grammar='verb')

    if legit == False:
        return err('verb')

    global verb
    verb = Verb

    return question('Thanks for the verb, and lastly I need an adverb.')

@ask.intent("AdverbIntent")
def adverb_intent(Adverb):
    legit =  checker(word=Adverb, grammar='adverb')

    if legit == False:
        return err('adverb')

    global noun
    global verb
    global adjective

    msg = """Thanks, here is your madlib: My {} has only gone and created an {}
    nightmare for me as it chose to {} the theory of
    relitivity {}.""".format(noun, adjective, verb, Adverb)

    return statement(msg)

@ask.intent("AMAZON.HelpIntent")
def help_intent():
    msg = """This skill takes an adjective, an adverb, a noun and a verb and
    produces a madlib for you to enjoy. Upon telling you your madlib the skill
    will close. Not sure what words to pick, why not try software, absolute,
    acknowledge and abnormally for the noun, adjective, verb and adverb
    respectively. To begin please give me a noun."""

    return question(msg)

def bye():
    bye_msg = "So long and thanks for all the fish!"
    return statement(bye_msg)

@ask.intent("AMAZON.StopIntent")
def stop_intent():
    return bye()

@ask.intent("AMAZON.CancelIntent")
def cancel_intent():
    return bye()

def err(grammer):
    plural = grammer + 's'
    msg = """The {} you provide is not in my list of {}.
    Please give me another {}.""".format(grammer, plural, grammer)

    return question(msg)

def checker(word, grammar):
    noun = ['people', 'history', 'way', 'art', 'world', 'information', 'map',
            'two', 'family', 'government', 'health', 'system', 'computer',
            'meat', 'year', 'thanks', 'music', 'person', 'reading', 'method',
            'data', 'food', 'understanding', 'theory', 'law', 'bird',
            'literature', 'problem', 'software', 'control', 'knowledge',
            'power', 'ability', 'economics', 'love', 'internet', 'television',
            'science', 'library', 'nature', 'fact', 'product', 'idea',
            'temperature', 'investment', 'area', 'society', 'activity', 'story',
            'industry', 'media', 'thing', 'oven', 'community', 'definition',
            'safety', 'quality', 'development', 'language', 'management',
            'player', 'variety', 'video', 'week', 'security', 'country', 'exam',
            'movie', 'organization', 'equipment', 'physics', 'analysis',
            'policy', 'series', 'thought', 'basis', 'boyfriend', 'direction',
            'strategy', 'technology', 'army', 'camera', 'freedom', 'paper',
            'environment', 'child', 'instance', 'month', 'truth', 'marketing',
            'university', 'writing', 'article', 'department', 'difference',
            'goal', 'news', 'audience', 'fishing', 'growth', 'income',
            'marriage', 'user', 'combination', 'failure', 'meaning', 'medicine',
            'philosophy', 'teacher', 'communication', 'night', 'chemistry',
            'disease', 'disk', 'energy', 'nation', 'road', 'role', 'soup',
            'advertising', 'location', 'success', 'addition', 'apartment',
            'education', 'math', 'moment', 'painting', 'politics', 'attention',
            'decision', 'event', 'property', 'shopping', 'student', 'wood',
            'competition', 'distribution', 'entertainment', 'office',
            'population', 'president', 'unit', 'category', 'cigarette',
            'context', 'introduction', 'opportunity', 'performance', 'driver',
            'flight', 'length', 'magazine', 'newspaper', 'relationship',
            'teaching', 'cell', 'dealer', 'finding', 'lake', 'member',
            'message', 'phone', 'scene', 'appearance', 'association', 'concept',
            'customer', 'death', 'discussion', 'housing', 'inflation',
            'insurance', 'mood', 'woman', 'advice', 'blood', 'effort',
            'expression', 'importance', 'opinion', 'payment', 'reality',
            'responsibility', 'situation', 'skill', 'statement', 'wealth',
            'application', 'city', 'county', 'depth', 'estate', 'foundation',
            'grandmother', 'heart', 'perspective', 'photo', 'recipe', 'studio',
            'topic', 'collection', 'depression', 'imagination', 'passion',
            'percentage', 'resource', 'setting', 'ad', 'agency', 'college',
            'connection', 'criticism', 'debt', 'description', 'memory',
            'patience', 'secretary', 'solution', 'administration', 'aspect',
            'attitude', 'director', 'personality', 'psychology',
            'recommendation', 'response', 'selection', 'storage', 'version',
            'alcohol', 'argument', 'complaint', 'contract', 'emphasis',
            'highway', 'loss', 'membership', 'possession', 'preparation',
            'steak', 'union', 'agreement', 'cancer', 'currency', 'employment',
            'engineering', 'entry', 'interaction', 'mixture', 'preference',
            'region', 'republic', 'tradition', 'virus', 'actor', 'classroom',
            'delivery', 'device', 'difficulty', 'drama', 'election', 'engine',
            'football', 'guidance', 'hotel', 'owner', 'priority', 'protection',
            'suggestion', 'tension', 'variation', 'anxiety', 'atmosphere',
            'awareness', 'bath', 'bread', 'candidate', 'climate', 'comparison',
            'confusion', 'construction', 'elevator', 'emotion', 'employee',
            'employer', 'guest', 'height', 'leadership', 'mall', 'manager',
            'operation', 'recording', 'sample', 'transportation', 'charity',
            'cousin', 'disaster', 'editor', 'efficiency', 'excitement',
            'extent', 'feedback', 'guitar', 'homework', 'leader', 'mom',
            'outcome', 'permission', 'presentation', 'promotion', 'reflection',
            'refrigerator', 'resolution', 'revenue', 'session', 'singer',
            'tennis', 'basket', 'bonus', 'cabinet', 'childhood', 'church',
            'clothes', 'coffee', 'dinner', 'drawing', 'hair', 'hearing',
            'initiative', 'judgment', 'lab', 'measurement', 'mode', 'mud',
            'orange', 'poetry', 'police', 'possibility', 'procedure', 'queen',
            'ratio', 'relation', 'restaurant', 'satisfaction', 'sector',
            'signature', 'significance', 'song', 'tooth', 'town', 'vehicle',
            'volume', 'wife', 'accident', 'airport', 'appointment', 'arrival',
            'assumption', 'baseball', 'chapter', 'committee', 'conversation',
            'database', 'enthusiasm', 'error', 'explanation', 'farmer', 'gate',
            'girl', 'hall', 'historian', 'hospital', 'injury', 'instruction',
            'maintenance', 'manufacturer', 'meal', 'perception', 'pie', 'poem',
            'presence', 'proposal', 'reception', 'replacement', 'revolution',
            'river', 'son', 'speech', 'tea', 'village', 'warning', 'winner',
            'worker', 'writer', 'assistance', 'breath', 'buyer', 'chest',
            'chocolate', 'conclusion', 'contribution', 'cookie', 'courage',
            'dad', 'desk', 'drawer', 'establishment', 'examination', 'garbage',
            'grocery', 'honey', 'impression', 'improvement', 'independence',
            'insect', 'inspection', 'inspector', 'king', 'ladder', 'menu',
            'penalty', 'piano', 'potato', 'profession', 'professor', 'quantity',
            'reaction', 'requirement', 'salad', 'sister', 'supermarket',
            'tongue', 'weakness', 'wedding', 'affair', 'ambition', 'analyst',
            'apple', 'assignment', 'assistant', 'bathroom', 'bedroom', 'beer',
            'birthday', 'celebration', 'championship', 'cheek', 'client',
            'consequence', 'departure', 'diamond', 'dirt', 'ear', 'fortune',
            'friendship', 'funeral', 'gene', 'girlfriend', 'hat', 'indication',
            'intention', 'lady', 'midnight', 'negotiation', 'obligation',
            'passenger', 'pizza', 'platform', 'poet', 'pollution',
            'recognition', 'reputation', 'shirt', 'sir', 'speaker', 'stranger',
            'surgery', 'sympathy', 'tale', 'throat', 'trainer', 'uncle',
            'youth', 'time', 'work', 'film', 'water', 'money', 'example',
            'while', 'business', 'study', 'game', 'life', 'form', 'air', 'day',
            'place', 'number', 'part', 'field', 'fish', 'back', 'process',
            'heat', 'hand', 'experience', 'job', 'book', 'end', 'point', 'type',
            'home', 'economy', 'value', 'body', 'market', 'guide', 'interest',
            'state', 'radio', 'course', 'company', 'price', 'size', 'card',
            'list', 'mind', 'trade', 'line', 'care', 'group', 'risk', 'word',
            'fat', 'force', 'key', 'light', 'training', 'name', 'school', 'top',
            'amount', 'level', 'order', 'practice', 'research', 'sense',
            'service', 'piece', 'web', 'boss', 'sport', 'fun', 'house', 'page',
            'term', 'test', 'answer', 'sound', 'focus', 'matter', 'kind',
            'soil', 'board', 'oil', 'picture', 'access', 'garden', 'range',
            'rate', 'reason', 'future', 'site', 'demand', 'exercise', 'image',
            'case', 'cause', 'coast', 'action', 'age', 'bad', 'boat', 'record',
            'result', 'section', 'building', 'mouse', 'cash', 'class',
            'nothing', 'period', 'plan', 'store', 'tax', 'side', 'subject',
            'space', 'rule', 'stock', 'weather', 'chance', 'figure', 'man',
            'model', 'source', 'beginning', 'earth', 'program', 'chicken',
            'design', 'feature', 'head', 'material', 'purpose', 'question',
            'rock', 'salt', 'act', 'birth', 'car', 'dog', 'object', 'scale',
            'sun', 'note', 'profit', 'rent', 'speed', 'style', 'war', 'bank',
            'craft', 'half', 'inside', 'outside', 'standard', 'bus', 'exchange',
            'eye', 'fire', 'position', 'pressure', 'stress', 'advantage',
            'benefit', 'box', 'frame', 'issue', 'step', 'cycle', 'face', 'item',
            'metal', 'paint', 'review', 'room', 'screen', 'structure', 'view',
            'account', 'ball', 'discipline', 'medium', 'share', 'balance',
            'bit', 'black', 'bottom', 'choice', 'gift', 'impact', 'machine',
            'shape', 'tool', 'wind', 'address', 'average', 'career', 'culture',
            'morning', 'pot', 'sign', 'table', 'task', 'condition', 'contact',
            'credit', 'egg', 'hope', 'ice', 'network', 'north', 'square',
            'attempt', 'date', 'effect', 'link', 'post', 'star', 'voice',
            'capital', 'challenge', 'friend', 'self', 'shot', 'brush', 'couple',
            'debate', 'exit', 'front', 'function', 'lack', 'living', 'plant',
            'plastic', 'spot', 'summer', 'taste', 'theme', 'track', 'wing',
            'brain', 'button', 'click', 'desire', 'foot', 'gas', 'influence',
            'notice', 'rain', 'wall', 'base', 'damage', 'distance', 'feeling',
            'pair', 'savings', 'staff', 'sugar', 'target', 'text', 'animal',
            'author', 'budget', 'discount', 'file', 'ground', 'lesson',
            'minute', 'officer', 'phase', 'reference', 'register', 'sky',
            'stage', 'stick', 'title', 'trouble', 'bowl', 'bridge', 'campaign',
            'character', 'club', 'edge', 'evidence', 'fan', 'letter', 'lock',
            'maximum', 'novel', 'option', 'pack', 'park', 'plenty', 'quarter',
            'skin', 'sort', 'weight', 'baby', 'background', 'carry', 'dish',
            'factor', 'fruit', 'glass', 'joint', 'master', 'muscle', 'red',
            'strength', 'traffic', 'trip', 'vegetable', 'appeal', 'chart',
            'gear', 'ideal', 'kitchen', 'land', 'log', 'mother', 'net', 'party',
            'principle', 'relative', 'sale', 'season', 'signal', 'spirit',
            'street', 'tree', 'wave', 'belt', 'bench', 'commission', 'copy',
            'drop', 'minimum', 'path', 'progress', 'project', 'sea', 'south',
            'status', 'stuff', 'ticket', 'tour', 'angle', 'blue', 'breakfast',
            'confidence', 'daughter', 'degree', 'doctor', 'dot', 'dream',
            'duty', 'essay', 'father', 'fee', 'finance', 'hour', 'juice',
            'limit', 'luck', 'milk', 'mouth', 'peace', 'pipe', 'seat', 'stable',
            'storm', 'substance', 'team', 'trick', 'afternoon', 'bat', 'beach',
            'blank', 'catch', 'chain', 'consideration', 'cream', 'crew',
            'detail', 'gold', 'interview', 'kid', 'mark', 'match', 'mission',
            'pain', 'pleasure', 'score', 'screw', 'sex', 'shop', 'shower',
            'suit', 'tone', 'window', 'agent', 'band', 'block', 'bone',
            'calendar', 'coat', 'contest', 'corner', 'court', 'district',
            'door', 'east', 'finger', 'garage', 'guarantee', 'hole', 'hook',
            'implement', 'layer', 'lecture', 'manner', 'meeting', 'nose',
            'parking', 'partner', 'profile', 'respect', 'rice', 'routine',
            'schedule', 'swimming', 'telephone', 'winter', 'airline', 'battle',
            'bill', 'bother', 'cake', 'code', 'curve', 'designer', 'dimension',
            'dress', 'ease', 'emergency', 'evening', 'extension', 'farm',
            'fight', 'grade', 'holiday', 'horror', 'horse', 'host', 'husband',
            'loan', 'mistake', 'mountain', 'nail', 'noise', 'occasion',
            'package', 'patient', 'pause', 'phrase', 'proof', 'race', 'relief',
            'sand', 'sentence', 'shoulder', 'smoke', 'stomach', 'string',
            'tourist', 'towel', 'vacation', 'west', 'wheel', 'wine', 'aside',
            'associate', 'blow', 'border', 'branch', 'breast', 'brother',
            'buddy', 'bunch', 'chip', 'coach', 'cross', 'document', 'draft',
            'dust', 'expert', 'floor', 'golf', 'habit', 'iron', 'judge',
            'knife', 'landscape', 'league', 'mail', 'mess', 'native', 'opening',
            'parent', 'pattern', 'pool', 'pound', 'request', 'salary', 'shame',
            'shelter', 'shoe', 'silver', 'tackle', 'tank', 'trust', 'assist',
            'bake', 'bell', 'bike', 'blame', 'brick', 'chair', 'closet', 'clue',
            'collar', 'comment', 'conference', 'devil', 'diet', 'fear', 'fuel',
            'glove', 'jacket', 'lunch', 'monitor', 'mortgage', 'nurse', 'pace',
            'panic', 'peak', 'plane', 'reward', 'sandwich', 'shock', 'spite',
            'spray', 'surprise', 'till', 'transition', 'weekend', 'welcome',
            'yard', 'alarm', 'bend', 'bicycle', 'bite', 'blind', 'bottle',
            'cable', 'candle', 'clerk', 'cloud', 'concert', 'counter', 'flower',
            'grandfather', 'harm', 'knee', 'lawyer', 'leather', 'load',
            'mirror', 'neck', 'pension', 'plate', 'purple', 'ruin', 'ship',
            'skirt', 'slice', 'snow', 'specialist', 'stroke', 'switch', 'trash',
            'tune', 'zone', 'anger', 'award', 'bitter', 'boot', 'camp', 'candy',
            'carpet', 'champion', 'channel', 'clock', 'comfort', 'crack',
            'engineer', 'entrance', 'fault', 'grass', 'hell', 'highlight',
            'incident', 'island', 'joke', 'jury', 'mate', 'motor', 'nerve',
            'passage', 'pride', 'priest', 'prize', 'promise', 'resident',
            'resort', 'ring', 'roof', 'rope', 'sail', 'scheme', 'script',
            'sock', 'station', 'tower', 'truck', 'witness', 'many', 'most',
            'other', 'make', 'good', 'look', 'great', 'being', 'still',
            'public', 'read', 'keep', 'start', 'give', 'human', 'local',
            'general', 'specific', 'long', 'play', 'feel', 'high', 'tonight',
            'common', 'change', 'simple', 'past', 'possible', 'particular',
            'today', 'major', 'personal', 'current', 'national', 'natural',
            'physical', 'show', 'check', 'second', 'call', 'move', 'increase',
            'single', 'individual', 'turn', 'guard', 'hold', 'main', 'offer',
            'potential', 'professional', 'international', 'travel', 'cook',
            'alternative', 'following', 'special', 'working', 'whole', 'dance',
            'excuse', 'cold', 'commercial', 'purchase', 'deal', 'primary',
            'worth', 'fall', 'necessary', 'positive', 'produce', 'search',
            'present', 'spend', 'talk', 'creative', 'tell', 'cost', 'drive',
            'green', 'support', 'glad', 'remove', 'return', 'complex',
            'effective', 'middle', 'regular', 'reserve', 'independent', 'leave',
            'original', 'reach', 'rest', 'serve', 'watch', 'beautiful',
            'charge', 'active', 'negative', 'safe', 'stay', 'visit', 'visual',
            'affect', 'cover', 'report', 'rise', 'walk', 'white', 'beyond',
            'junior', 'pick', 'unique', 'anything', 'classic', 'final', 'lift',
            'private', 'teach', 'western', 'concern', 'familiar',
            'official', 'broad', 'comfortable', 'gain', 'maybe', 'rich', 'save',
            'stand', 'young', 'fail', 'heavy', 'hello', 'lead', 'listen',
            'valuable', 'worry', 'handle', 'leading', 'meet', 'release', 'sell',
            'finish', 'normal', 'press', 'ride', 'secret', 'spread', 'spring',
            'tough', 'wait', 'brown', 'deep', 'display', 'flow', 'objective',
            'shoot', 'touch', 'chemical', 'dump', 'extreme', 'push',
            'conflict', 'fill', 'formal', 'jump', 'kick', 'opposite', 'pass',
            'pitch', 'remote', 'total', 'treat', 'vast', 'abuse', 'beat',
            'burn', 'deposit', 'print', 'sleep', 'somewhere', 'advance',
            'anywhere', 'consist', 'dark', 'double', 'draw', 'equal', 'hire',
            'internal', 'join', 'kill', 'sensitive', 'attack', 'claim',
            'constant', 'drag', 'drink', 'guess', 'minor', 'pull', 'soft',
            'solid', 'wear', 'weird', 'wonder', 'annual', 'count', 'dead',
            'doubt', 'feed', 'forever', 'impress', 'nobody', 'repeat', 'round',
            'sing', 'slide', 'strip', 'whereas', 'wish', 'combine', 'command',
            'dig', 'divide', 'equivalent', 'hang', 'hunt', 'initial', 'march',
            'mention', 'smell', 'spiritual', 'survey', 'tie', 'adult', 'brief',
            'crazy', 'escape', 'gather', 'hate', 'prior', 'repair', 'rough',
            'sad', 'scratch', 'sick', 'strike', 'employ', 'external', 'hurt',
            'illegal', 'laugh', 'lay', 'mobile', 'nasty', 'ordinary', 'respond',
            'royal', 'senior', 'split', 'strain', 'struggle', 'swim', 'train',
            'upper', 'wash', 'yellow', 'convert', 'crash', 'dependent', 'fold',
            'funny', 'grab', 'hide', 'miss', 'permit', 'quote', 'recover',
            'resolve', 'roll', 'sink', 'slip', 'spare', 'suspect', 'sweet',
            'swing', 'twist', 'upstairs', 'usual', 'abroad', 'brave', 'calm',
            'concentrate', 'estimate', 'grand', 'male', 'mine', 'prompt',
            'quiet', 'refuse', 'regret', 'reveal', 'rush', 'shake', 'shift',
            'shine', 'steal', 'suck', 'surround', 'anybody', 'bear',
            'brilliant', 'dare', 'dear', 'delay', 'drunk', 'female', 'hurry',
            'inevitable', 'invite', 'kiss', 'neat', 'punch', 'quit', 'reply',
            'representative', 'resist', 'rip', 'rub', 'silly', 'smile', 'spell',
            'stretch', 'stupid', 'tear', 'temporary', 'tomorrow', 'wake',
            'wrap', 'yesterday']

    adjective = ['abandoned', 'able', 'absolute', 'adorable', 'adventurous',
                 'academic', 'acceptable', 'acclaimed', 'accomplished',
                 'accurate', 'aching', 'acidic', 'acrobatic', 'active',
                 'actual', 'adept', 'admirable', 'admired', 'adolescent',
                 'adorable', 'adored', 'advanced', 'afraid', 'affectionate',
                 'aged', 'aggravating', 'aggressive', 'agile', 'agitated',
                 'agonizing', 'agreeable', 'ajar', 'alarmed', 'alarming',
                 'alert', 'alienated', 'alive', 'all', 'altruistic', 'amazing',
                 'ambitious', 'ample', 'amused', 'amusing', 'anchored',
                 'ancient', 'angelic', 'angry', 'anguished', 'animated',
                 'annual', 'another', 'antique', 'anxious', 'any',
                 'apprehensive', 'appropriate', 'apt', 'arctic', 'arid',
                 'aromatic', 'artistic', 'ashamed', 'assured', 'astonishing',
                 'athletic', 'attached', 'attentive', 'attractive', 'austere',
                 'authentic', 'authorized', 'automatic', 'avaricious',
                 'average', 'aware', 'awesome', 'awful', 'awkward', 'babyish',
                 'bad', 'back', 'baggy', 'bare', 'barren', 'basic', 'beautiful',
                 'belated', 'beloved', 'beneficial', 'better', 'best',
                 'bewitched', 'big', 'big hearted', 'biodegradable',
                 'bite sized', 'bitter', 'black', 'black and white', 'bland',
                 'blank', 'blaring', 'bleak', 'blind', 'blissful', 'blond',
                 'blue', 'blushing', 'bogus', 'boiling', 'bold', 'bony',
                 'boring', 'bossy', 'both', 'bouncy', 'bountiful', 'bowed',
                 'brave', 'breakable', 'brief', 'bright', 'brilliant', 'brisk',
                 'broken', 'bronze', 'brown', 'bruised', 'bubbly', 'bulky',
                 'bumpy', 'buoyant', 'burdensome', 'burly', 'bustling', 'busy',
                 'buttery', 'buzzing', 'calculating', 'calm', 'candid',
                 'canine', 'capital', 'carefree', 'careful', 'careless',
                 'caring', 'cautious', 'cavernous', 'celebrated', 'charming',
                 'cheap', 'cheerful', 'cheery', 'chief', 'chilly', 'chubby',
                 'circular', 'classic', 'clean', 'clear', 'clear cut', 'clever',
                 'close', 'closed', 'cloudy', 'clueless', 'clumsy', 'cluttered',
                 'coarse', 'cold', 'colorful', 'colorless', 'colossal',
                 'comfortable', 'common', 'compassionate', 'competent',
                 'complete', 'complex', 'complicated', 'composed', 'concerned',
                 'concrete', 'confused', 'conscious', 'considerate', 'constant',
                 'content', 'conventional', 'cooked', 'cool', 'cooperative',
                 'coordinated', 'corny', 'corrupt', 'costly', 'courageous',
                 'courteous', 'crafty', 'crazy', 'creamy', 'creative', 'creepy',
                 'criminal', 'crisp', 'critical', 'crooked', 'crowded', 'cruel',
                 'crushing', 'cuddly', 'cultivated', 'cultured', 'cumbersome',
                 'curly', 'curvy', 'cute', 'cylindrical', 'damaged', 'damp',
                 'dangerous', 'dapper', 'daring', 'darling', 'dark', 'dazzling',
                 'dead', 'deadly', 'deafening', 'dear', 'dearest', 'decent',
                 'decimal', 'decisive', 'deep', 'defenseless', 'defensive',
                 'defiant', 'deficient', 'definite', 'definitive', 'delayed',
                 'delectable', 'delicious', 'delightful', 'delirious',
                 'demanding', 'dense', 'dental', 'dependable', 'dependent',
                 'descriptive', 'deserted', 'detailed', 'determined', 'devoted',
                 'different', 'difficult', 'digital', 'diligent', 'dim',
                 'dimpled', 'dimwitted', 'direct', 'disastrous', 'discrete',
                 'disfigured', 'disgusting', 'disloyal', 'dismal', 'distant',
                 'downright', 'dreary', 'dirty', 'disguised', 'dishonest',
                 'distinct', 'distorted', 'dizzy', 'dopey',
                 'doting', 'double', 'downright', 'drab', 'drafty', 'dramatic',
                 'dreary', 'droopy', 'dry', 'dual', 'dull', 'dutiful', 'each',
                 'eager', 'earnest', 'early', 'easy', 'easy going', 'ecstatic',
                 'edible', 'educated', 'elaborate', 'elastic', 'elated',
                 'elderly', 'electric', 'elegant', 'elementary', 'elliptical',
                 'embarrassed', 'embellished', 'eminent', 'emotional', 'empty',
                 'enchanted', 'enchanting', 'energetic', 'enlightened',
                 'enormous', 'enraged', 'entire', 'envious', 'equal',
                 'equatorial', 'essential', 'esteemed', 'ethical', 'euphoric',
                 'even', 'evergreen', 'everlasting', 'every', 'evil', 'exalted',
                 'excellent', 'exemplary', 'exhausted', 'excitable', 'excited',
                 'exciting', 'exotic', 'expensive', 'experienced', 'expert',
                 'extraneous', 'extroverted', 'extra large', 'extra small',
                 'fabulous', 'failing', 'faint', 'fair', 'faithful', 'fake',
                 'false', 'familiar', 'famous', 'fancy', 'fantastic', 'far',
                 'faraway', 'far flung', 'far off', 'fast', 'fat', 'fatal',
                 'fatherly', 'favorable', 'favorite', 'fearful', 'fearless',
                 'feisty', 'feline', 'female', 'feminine', 'few', 'fickle',
                 'filthy', 'fine', 'finished', 'firm', 'first', 'firsthand',
                 'fitting', 'fixed', 'flaky', 'flamboyant', 'flashy', 'flat',
                 'flawed', 'flawless', 'flickering', 'flimsy', 'flippant',
                 'flowery', 'fluffy', 'fluid', 'flustered', 'focused', 'fond',
                 'foolhardy', 'foolish', 'forceful', 'forked', 'formal',
                 'forsaken', 'forthright', 'fortunate', 'fragrant', 'frail',
                 'frank', 'frayed', 'free', 'French', 'fresh', 'frequent',
                 'friendly', 'frightened', 'frightening', 'frigid', 'frilly',
                 'frizzy', 'frivolous', 'front', 'frosty', 'frozen', 'frugal',
                 'fruitful', 'full', 'fumbling', 'functional', 'funny', 'fussy',
                 'fuzzy', 'gargantuan', 'gaseous', 'general', 'generous',
                 'gentle', 'genuine', 'giant', 'giddy', 'gigantic', 'gifted',
                 'giving', 'glamorous', 'glaring', 'glass', 'gleaming',
                 'gleeful', 'glistening', 'glittering', 'gloomy', 'glorious',
                 'glossy', 'glum', 'golden', 'good', 'good natured', 'gorgeous',
                 'graceful', 'gracious', 'grand', 'grandiose', 'granular',
                 'grateful', 'grave', 'gray', 'great', 'greedy', 'green',
                 'gregarious', 'grim', 'grimy', 'gripping', 'grizzled', 'gross',
                 'grotesque', 'grouchy', 'grounded', 'growing', 'growling',
                 'grown', 'grubby', 'gruesome', 'grumpy', 'guilty', 'gullible',
                 'gummy', 'hairy', 'half', 'handmade', 'handsome', 'handy',
                 'happy', 'happy go lucky', 'hard', 'hard to find', 'harmful',
                 'harmless', 'harmonious', 'harsh', 'hasty', 'hateful',
                 'haunting', 'healthy', 'heartfelt', 'hearty', 'heavenly',
                 'heavy', 'hefty', 'helpful', 'helpless', 'hidden', 'hideous',
                 'high', 'high level', 'hilarious', 'hoarse', 'hollow',
                 'homely', 'honest', 'honorable', 'honored', 'hopeful',
                 'horrible', 'hospitable', 'hot', 'huge', 'humble',
                 'humiliating', 'humming', 'humongous', 'hungry', 'hurtful',
                 'husky', 'icky', 'icy', 'ideal', 'idealistic', 'identical',
                 'idle', 'idiotic', 'idolized', 'ignorant', 'ill', 'illegal',
                 'ill fated', 'ill informed', 'illiterate', 'illustrious',
                 'imaginary', 'imaginative', 'immaculate', 'immaterial',
                 'immediate', 'immense', 'impassioned', 'impeccable',
                 'impartial', 'imperfect', 'imperturbable', 'impish',
                 'impolite', 'important', 'impossible', 'impractical',
                 'impressionable', 'impressive', 'improbable', 'impure',
                 'inborn', 'incomparable', 'incompatible', 'incomplete',
                 'inconsequential', 'incredible', 'indelible', 'inexperienced',
                 'indolent', 'infamous', 'infantile', 'infatuated', 'inferior',
                 'infinite', 'informal', 'innocent', 'insecure', 'insidious',
                 'insignificant', 'insistent', 'instructive', 'insubstantial',
                 'intelligent', 'intent', 'intentional', 'interesting',
                 'internal', 'international', 'intrepid', 'ironclad',
                 'irresponsible', 'irritating', 'itchy', 'jaded', 'jagged',
                 'jam packed', 'jaunty', 'jealous', 'jittery', 'joint', 'jolly',
                 'jovial', 'joyful', 'joyous', 'jubilant', 'judicious', 'juicy',
                 'jumbo', 'junior', 'jumpy', 'juvenile', 'kaleidoscopic',
                 'keen', 'key', 'kind', 'kindhearted', 'kindly', 'klutzy',
                 'knobby', 'knotty', 'knowledgeable', 'knowing', 'known',
                 'kooky', 'kosher', 'lame', 'lanky', 'large', 'last', 'lasting',
                 'late', 'lavish', 'lawful', 'lazy', 'leading', 'lean', 'leafy',
                 'left', 'legal', 'legitimate', 'light', 'lighthearted',
                 'likable', 'likely', 'limited', 'limp', 'limping', 'linear',
                 'lined', 'liquid', 'little', 'live', 'lively', 'livid',
                 'loathsome', 'lone', 'lonely', 'long', 'long term', 'loose',
                 'lopsided', 'lost', 'loud', 'lovable', 'lovely', 'loving',
                 'low', 'loyal', 'lucky', 'lumbering', 'luminous', 'lumpy',
                 'lustrous', 'luxurious', 'mad', 'made up', 'magnificent',
                 'majestic', 'major', 'male', 'mammoth', 'married', 'marvelous',
                 'masculine', 'massive', 'mature', 'meager', 'mealy', 'mean',
                 'measly', 'meaty', 'medical', 'mediocre', 'medium', 'meek',
                 'mellow', 'melodic', 'memorable', 'menacing', 'merry', 'messy',
                 'metallic', 'mild', 'milky', 'mindless', 'miniature', 'minor',
                 'minty', 'miserable', 'miserly', 'misguided', 'misty', 'mixed',
                 'modern', 'modest', 'moist', 'monstrous', 'monthly',
                 'monumental', 'moral', 'mortified', 'motherly', 'motionless',
                 'mountainous', 'muddy', 'muffled', 'multicolored', 'mundane',
                 'murky', 'mushy', 'musty', 'muted', 'mysterious', 'naive',
                 'narrow', 'nasty', 'natural', 'naughty', 'nautical', 'near',
                 'neat', 'necessary', 'needy', 'negative', 'neglected',
                 'negligible', 'neighboring', 'nervous', 'new', 'next', 'nice',
                 'nifty', 'nimble', 'nippy', 'nocturnal', 'noisy', 'nonstop',
                 'normal', 'notable', 'noted', 'noteworthy', 'novel', 'noxious',
                 'numb', 'nutritious', 'nutty', 'obedient', 'obese', 'oblong',
                 'oily', 'oblong', 'obvious', 'occasional', 'odd', 'oddball',
                 'offbeat', 'offensive', 'official', 'old', 'old fashioned',
                 'only', 'open', 'optimal', 'optimistic', 'opulent', 'orange',
                 'orderly', 'organic', 'ornate', 'ornery', 'ordinary',
                 'original', 'other', 'our', 'outlying', 'outgoing',
                 'outlandish', 'outrageous', 'outstanding', 'oval',
                 'overcooked', 'overdue', 'overjoyed', 'overlooked',
                 'palatable', 'pale', 'paltry', 'parallel', 'parched',
                 'partial', 'passionate', 'past', 'pastel', 'peaceful',
                 'peppery', 'perfect', 'perfumed', 'periodic', 'perky',
                 'personal', 'pertinent', 'pesky', 'pessimistic', 'petty',
                 'phony', 'physical', 'piercing', 'pink', 'pitiful', 'plain',
                 'plaintive', 'plastic', 'playful', 'pleasant', 'pleased',
                 'pleasing', 'plump', 'plush', 'polished', 'polite',
                 'political', 'pointed', 'pointless', 'poised', 'poor',
                 'popular', 'portly', 'posh', 'positive', 'possible', 'potable',
                 'powerful', 'powerless', 'practical', 'precious', 'present',
                 'prestigious', 'pretty', 'precious', 'previous', 'pricey',
                 'prickly', 'primary', 'prime', 'pristine', 'private', 'prize',
                 'probable', 'productive', 'profitable', 'profuse', 'proper',
                 'proud', 'prudent', 'punctual', 'pungent', 'puny', 'pure',
                 'purple', 'pushy', 'putrid', 'puzzled', 'puzzling', 'quaint',
                 'qualified', 'quarrelsome', 'quarterly', 'queasy', 'querulous',
                 'questionable', 'quick', 'quick witted', 'quiet',
                 'quintessential', 'quirky', 'quixotic', 'quizzical', 'radiant',
                 'ragged', 'rapid', 'rare', 'rash', 'raw', 'recent', 'reckless',
                 'rectangular', 'ready', 'real', 'realistic', 'reasonable',
                 'red', 'reflecting', 'regal', 'regular', 'reliable',
                 'relieved', 'remarkable', 'remorseful', 'remote', 'repentant',
                 'required', 'respectful', 'responsible', 'repulsive',
                 'revolving', 'rewarding', 'rich', 'rigid', 'right', 'ringed',
                 'ripe', 'roasted', 'robust', 'rosy', 'rotating', 'rotten',
                 'rough', 'round', 'rowdy', 'royal', 'rubbery', 'rundown',
                 'ruddy', 'rude', 'runny', 'rural', 'rusty', 'sad', 'safe',
                 'salty', 'same', 'sandy', 'sane', 'sarcastic', 'sardonic',
                 'satisfied', 'scaly', 'scarce', 'scared', 'scary', 'scented',
                 'scholarly', 'scientific', 'scornful', 'scratchy', 'scrawny',
                 'second', 'secondary', 'second hand', 'secret', 'self assured',
                 'self reliant', 'selfish', 'sentimental', 'separate', 'serene',
                 'serious', 'serpentine', 'several', 'severe', 'shabby',
                 'shadowy', 'shady', 'shallow', 'shameful', 'shameless',
                 'sharp', 'shimmering', 'shiny', 'shocked', 'shocking',
                 'shoddy', 'short', 'short term', 'showy', 'shrill', 'shy',
                 'sick', 'silent', 'silky', 'silly', 'silver', 'similar',
                 'simple', 'simplistic', 'sinful', 'single', 'sizzling',
                 'skeletal', 'skinny', 'sleepy', 'slight', 'slim', 'slimy',
                 'slippery', 'slow', 'slushy', 'small', 'smart', 'smoggy',
                 'smooth', 'smug', 'snappy', 'snarling', 'sneaky', 'sniveling',
                 'snoopy', 'sociable', 'soft', 'soggy', 'solid', 'somber',
                 'some', 'spherical', 'sophisticated', 'sore', 'sorrowful',
                 'soulful', 'soupy', 'sour', 'Spanish', 'sparkling', 'sparse',
                 'specific', 'spectacular', 'speedy', 'spicy', 'spiffy',
                 'spirited', 'spiteful', 'splendid', 'spotless', 'spotted',
                 'spry', 'square', 'squeaky', 'squiggly', 'stable', 'staid',
                 'stained', 'stale', 'standard', 'starchy', 'stark', 'starry',
                 'steep', 'sticky', 'stiff', 'stimulating', 'stingy', 'stormy',
                 'straight', 'strange', 'steel', 'strict', 'strident',
                 'striking', 'striped', 'strong', 'studious', 'stunning',
                 'stupendous', 'stupid', 'sturdy', 'stylish', 'subdued',
                 'submissive', 'substantial', 'subtle', 'suburban', 'sudden',
                 'sugary', 'sunny', 'super', 'superb', 'superficial',
                 'superior', 'supportive', 'sure footed', 'surprised',
                 'suspicious', 'svelte', 'sweaty', 'sweet', 'sweltering',
                 'swift', 'sympathetic', 'tall', 'talkative', 'tame', 'tan',
                 'tangible', 'tart', 'tasty', 'tattered', 'taut', 'tedious',
                 'teeming', 'tempting', 'tender', 'tense', 'tepid', 'terrible',
                 'terrific', 'testy', 'thankful', 'that', 'these', 'thick',
                 'thin', 'third', 'thirsty', 'this', 'thorough', 'thorny',
                 'those', 'thoughtful', 'threadbare', 'thrifty', 'thunderous',
                 'tidy', 'tight', 'timely', 'tinted', 'tiny', 'tired', 'torn',
                 'total', 'tough', 'traumatic', 'treasured', 'tremendous',
                 'tragic', 'trained', 'tremendous', 'triangular', 'tricky',
                 'trifling', 'trim', 'trivial', 'troubled', 'true', 'trusting',
                 'trustworthy', 'trusty', 'truthful', 'tubby', 'turbulent',
                 'twin', 'ugly', 'ultimate', 'unacceptable', 'unaware',
                 'uncomfortable', 'uncommon', 'unconscious', 'understated',
                 'unequaled', 'uneven', 'unfinished', 'unfit', 'unfolded',
                 'unfortunate', 'unhappy', 'unhealthy', 'uniform',
                 'unimportant', 'unique', 'united', 'unkempt', 'unknown',
                 'unlawful', 'unlined', 'unlucky', 'unnatural', 'unpleasant',
                 'unrealistic', 'unripe', 'unruly', 'unselfish', 'unsightly',
                 'unsteady', 'unsung', 'untidy', 'untimely', 'untried',
                 'untrue', 'unused', 'unusual', 'unwelcome', 'unwieldy',
                 'unwilling', 'unwitting', 'unwritten', 'upbeat', 'upright',
                 'upset', 'urban', 'usable', 'used', 'useful', 'useless',
                 'utilized', 'utter', 'vacant', 'vague', 'vain', 'valid',
                 'valuable', 'vapid', 'variable', 'vast', 'velvety',
                 'venerated', 'vengeful', 'verifiable', 'vibrant', 'vicious',
                 'victorious', 'vigilant', 'vigorous', 'villainous', 'violet',
                 'violent', 'virtual', 'virtuous', 'visible', 'vital',
                 'vivacious', 'vivid', 'voluminous', 'wan', 'warlike', 'warm',
                 'warmhearted', 'warped', 'wary', 'wasteful', 'watchful',
                 'waterlogged', 'watery', 'wavy', 'wealthy', 'weak', 'weary',
                 'webbed', 'wee', 'weekly', 'weepy', 'weighty', 'weird',
                 'welcome', 'well documented', 'well groomed', 'well informed',
                 'well lit', 'well made', 'well off', 'well to do', 'well worn',
                 'wet', 'which', 'whimsical', 'whirlwind', 'whispered', 'white',
                 'whole', 'whopping', 'wicked', 'wide', 'wide eyed', 'wiggly',
                 'wild', 'willing', 'wilted', 'winding', 'windy', 'winged',
                 'wiry', 'wise', 'witty', 'wobbly', 'woeful', 'wonderful',
                 'wooden', 'woozy', 'wordy', 'worldly', 'worn', 'worried',
                 'worrisome', 'worse', 'worst', 'worthless', 'worthwhile',
                 'worthy', 'wrathful', 'wretched', 'writhing', 'wrong', 'wry',
                 'yawning', 'yearly', 'yellow', 'yellowish', 'young',
                 'youthful', 'yummy', 'zany', 'zealous', 'zesty', 'zigzag']

    verb = ['accept', 'ache', 'acknowledge', 'act', 'add', 'admire', 'admit',
            'admonish', 'advise', 'adopt', 'affirm', 'afford', 'agree', 'ail',
            'alert', 'allege', 'allow', 'allude', 'amuse', 'analyze',
            'announce', 'annoy', 'answer', 'apologize', 'appeal', 'appear',
            'applaud', 'appreciate', 'approve', 'argue', 'arrange', 'arrest',
            'arrive', 'articulate', 'ask', 'assert', 'assure', 'attach',
            'attack', 'attempt', 'attend', 'attract', 'auction', 'avoid',
            'avow', 'awake', 'babble', 'back', 'bake', 'balance', 'balk', 'ban',
            'bang', 'bandage', 'bar', 'bare', 'bargain', 'bark', 'barrage',
            'barter', 'baste', 'bat', 'bathe',
            'battle', 'bawl', 'be', 'beam', 'bear', 'beat', 'become',
            'befriend', 'beg', 'begin', 'behave', 'believe', 'bellow', 'belong',
            'bend', 'berate', 'besiege', 'bestow', 'bet', 'bid', 'bite',
            'bleach', 'bleed', 'bless', 'blind', 'blink', 'blot', 'blow',
            'blurt', 'blush', 'boast', 'bob', 'boil', 'bolt', 'bomb', 'book',
            'bore', 'borrow', 'bounce', 'bow', 'box', 'brag', 'brake', 'branch',
            'brand', 'break', 'breathe', 'breed', 'bring', 'broadcast', 'broil',
            'bruise', 'brush', 'bubble', 'build', 'bump', 'burn', 'burnish',
            'bury', 'buy', 'buzz', 'cajole', 'calculate', 'call', 'camp',
            'care', 'carry', 'carve', 'cause', 'caution', 'catch', 'challenge',
            'change', 'chant', 'charge', 'chase', 'cheat', 'check', 'cheer',
            'chew', 'chide', 'chip', 'choke', 'chomp', 'choose', 'chop',
            'claim', 'clap', 'clean', 'clear', 'climb', 'clip', 'close',
            'coach', 'coil', 'collect', 'color', 'comb', 'come', 'comfort',
            'command', 'comment', 'communicate', 'compare', 'compete',
            'complain', 'complete', 'concede', 'concentrate', 'concern',
            'conclude', 'concur', 'confess', 'confide', 'confirm', 'connect',
            'consent', 'consider', 'consist', 'contain', 'contend', 'continue',
            'cook', 'copy', 'correct', 'cost', 'cough', 'count', 'counter',
            'cover', 'covet', 'crack', 'crash', 'crave', 'crawl', 'crochet',
            'cross', 'criticize', 'croak', 'cross examine', 'crowd', 'crush',
            'cry', 'cure', 'curl', 'curse', 'curve', 'cut', 'cycle', 'dam',
            'damage', 'dance', 'dare', 'deal', 'debate', 'decay', 'deceive',
            'decide', 'decipher', 'declare', 'decorate', 'delay', 'delight',
            'deliver', 'demand', 'deny', 'depend', 'describe', 'desert',
            'deserve', 'desire', 'deter', 'develop', 'dial', 'dictate', 'die',
            'dig', 'digress', 'direct', 'disclose', 'dislike', 'dive', 'divide',
            'divorce', 'divulge', 'do', 'dock', 'dole', 'dote', 'double',
            'doubt', 'drag', 'drain', 'draw', 'dream', 'dress', 'drip', 'drill',
            'drink', 'drive', 'drone', 'drop', 'drown', 'dry', 'dupe', 'dump',
            'dust', 'dye', 'earn', 'eat', 'echo', 'edit', 'educate', 'elope',
            'embarrass', 'emigrate', 'emit', 'emphasize', 'employ', 'empty',
            'enchant', 'encode', 'encourage', 'end', 'enjoin', 'enjoy', 'enter',
            'entertain', 'enunciate', 'envy', 'equivocate', 'escape',
            'evacuate', 'evaporate', 'exaggerate', 'examine', 'excite',
            'exclaim', 'excuse', 'exercise', 'exist', 'expand', 'expect',
            'expel', 'exhort', 'explain', 'explode', 'explore', 'extend',
            'extoll', 'face', 'fade', 'fail', 'fall', 'falter', 'fasten',
            'favor', 'fax', 'fear', 'feed', 'feel', 'fence', 'fetch', 'fight',
            'file', 'fill', 'film', 'find', 'fire', 'fish', 'fit', 'fix',
            'flap', 'flash', 'flee', 'float', 'flood', 'floss', 'flow',
            'flower', 'fly', 'fold', 'follow', 'fool', 'force', 'foretell',
            'forget', 'forgive', 'form', 'found', 'frame', 'freeze', 'fret',
            'frighten', 'fry', 'fume', 'garden', 'gasp', 'gather', 'gaze',
            'gel', 'get', 'gild', 'give', 'glide', 'glue', 'gnaw', 'go', 'grab',
            'grate', 'grease', 'greet', 'grill', 'grin', 'grip', 'groan',
            'grow', 'growl', 'grumble', 'grunt', 'guarantee', 'guard', 'guess',
            'guide', 'gurgle', 'gush', 'hail', 'hammer', 'hand', 'handle',
            'hang', 'happen', 'harass', 'harm', 'harness', 'hate', 'haunt',
            'have', 'head', 'heal', 'heap', 'hear', 'heat', 'hide',
            'highlight', 'hijack', 'hinder', 'hint', 'hiss', 'hit', 'hold',
            'hook', 'hoot', 'hop', 'hope', 'hover', 'howl', 'hug', 'hum',
            'hunt', 'hurry', 'hurt', 'ice', 'identify', 'ignore', 'imagine',
            'immigrate', 'imply', 'implore', 'impress', 'improve', 'include',
            'increase', 'infect', 'inflate', 'influence', 'inform', 'infuse',
            'inject', 'injure', 'inquire', 'insist', 'inspect', 'inspire',
            'instruct', 'intend', 'interest', 'interfere', 'interject',
            'interrupt', 'introduce', 'invent', 'invest', 'invite', 'irritate',
            'iron', 'itch', 'jab', 'jabber', 'jail', 'jam', 'jeer', 'jest',
            'jog', 'join', 'joke', 'jolt', 'judge', 'juggle', 'jump', 'keep',
            'kick', 'kill', 'kiss', 'kneel', 'knit', 'knock', 'knot', 'know',
            'label', 'lament', 'land', 'last', 'laugh', 'lay', 'lead', 'lean',
            'learn', 'leave', 'lecture', 'lend', 'let', 'level', 'license',
            'lick', 'lie', 'lift', 'light', 'lighten', 'like', 'list', 'listen',
            'live', 'load', 'loan', 'lock', 'long', 'look', 'loosen', 'lose',
            'love', 'lower', 'mail', 'maintain', 'make', 'man', 'manage', 'mar',
            'march', 'mark', 'marry', 'marvel', 'mate', 'matter', 'mean',
            'measure', 'meet', 'melt', 'memorize', 'mend', 'mention', 'merge',
            'milk', 'mine', 'miss', 'mix', 'moan', 'moor', 'mourn', 'molt',
            'move', 'mow', 'mug', 'multiply', 'mumble', 'murder', 'mutter',
            'nag', 'nail', 'name', 'nap', 'need', 'nest', 'nod', 'note',
            'notice', 'number', 'obey', 'object', 'observe', 'obtain', 'occur',
            'offend', 'offer', 'ogle', 'oil', 'omit', 'open', 'operate',
            'order', 'overflow', 'overrun', 'owe', 'own', 'pack', 'pad',
            'paddle', 'paint', 'pant', 'park', 'part', 'pass', 'paste', 'pat',
            'pause', 'pay', 'peck', 'pedal', 'peel', 'peep', 'peer', 'peg',
            'pelt', 'perform', 'permit', 'pester', 'pet', 'phone', 'pick',
            'pinch', 'pine', 'place', 'plan', 'plant', 'play', 'plead',
            'please', 'pledge', 'plow', 'plug', 'point', 'poke', 'polish',
            'ponder', 'pop', 'possess', 'post', 'postulate', 'pour', 'practice',
            'pray', 'preach', 'precede', 'predict', 'prefer', 'prepare',
            'present', 'preserve', 'press', 'pretend', 'prevent', 'prick',
            'print', 'proceed', 'proclaim', 'produce', 'profess', 'program',
            'promise', 'propose', 'protect', 'protest', 'provide', 'pry',
            'pull', 'pump', 'punch', 'puncture', 'punish', 'push', 'put',
            'question', 'quilt', 'quit', 'quiz', 'quote', 'race', 'radiate',
            'rain', 'raise', 'rant', 'rain', 'rate', 'rave', 'reach', 'realize',
            'read', 'rebuff', 'recall', 'receive', 'recite', 'recognize',
            'recommend', 'record', 'reduce', 'reflect', 'refuse', 'regret',
            'reign', 'reiterate', 'reject', 'rejoice', 'relate', 'relax',
            'release', 'rely', 'remain', 'remember', 'remind', 'remove',
            'repair', 'repeat', 'replace', 'reply', 'report', 'reprimand',
            'reproduce', 'request', 'rescue', 'retire', 'retort', 'return',
            'reveal', 'reverse', 'rhyme', 'ride', 'ring', 'rinse', 'rise',
            'risk', 'roar', 'rob', 'rock', 'roll', 'rot', 'row', 'rub', 'ruin',
            'rule', 'run', 'rush', 'sack', 'sail', 'satisfy', 'save', 'savor',
            'saw', 'say', 'scare', 'scatter', 'scoff', 'scold', 'scoot',
            'scorch', 'scrape', 'scratch', 'scream', 'screech', 'screw',
            'scribble', 'seal', 'search', 'see', 'sell', 'send', 'sense',
            'separate', 'serve', 'set', 'settle', 'sever', 'sew', 'shade',
            'shampoo', 'share', 'shave', 'shelter', 'shift', 'shiver', 'shock',
            'shoot', 'shop', 'shout', 'show', 'shriek', 'shrug', 'shut', 'sigh',
            'sign', 'signal', 'sin', 'sing', 'singe', 'sip', 'sit', 'skate',
            'skateboard', 'sketch', 'ski', 'skip', 'slap', 'sleep', 'slice',
            'slide', 'slip', 'slow', 'smash', 'smell', 'smile', 'smoke', 'snap',
            'snarl', 'snatch', 'sneak', 'sneer', 'sneeze', 'snicker', 'sniff',
            'snore', 'snort', 'snoop', 'snooze', 'snow', 'soak', 'sob',
            'soothe', 'sound', 'sow', 'span', 'spare', 'spark', 'sparkle',
            'speak', 'speculate', 'spell', 'spend', 'spill', 'spin', 'spoil',
            'spot', 'spray', 'sprout', 'sputter', 'squash', 'squeeze', 'stab',
            'stain', 'stammer', 'stamp', 'stand', 'star', 'stare', 'start',
            'stash', 'state', 'stay', 'steer', 'step', 'stipulate', 'stir',
            'stitch', 'store', 'strap', 'storm', 'stow', 'strengthen',
            'stress', 'stretch', 'strip', 'stroke', 'stuff', 'stutter', 'stray',
            'strum', 'strut', 'stun', 'stunt', 'submerge', 'succeed', 'suffer',
            'suggest', 'suit', 'supply', 'support', 'suppose', 'surmise',
            'surprise', 'surround', 'suspect', 'suspend', 'sway', 'swear',
            'swim', 'swing', 'switch', 'swoop', 'sympathize', 'talk', 'take',
            'tame', 'tap', 'taste', 'taunt', 'teach', 'tear', 'tease',
            'telephone', 'tell', 'tempt', 'terrify', 'test', 'testify', 'thank',
            'thaw', 'theorize', 'think', 'threaten', 'throw', 'thunder', 'tick',
            'tickle', 'tie', 'time', 'tip', 'tire', 'toast', 'toss', 'touch',
            'tour', 'tow', 'trace', 'track', 'trade', 'train', 'translate',
            'transport', 'trap', 'travel', 'treat', 'tremble', 'trick',
            'trickle', 'trim', 'trip', 'trot', 'trouble', 'trust', 'trounce',
            'try', 'tug', 'tumble', 'turn', 'twist', 'type', 'understand',
            'undress', 'unfasten', 'unite', 'unlock', 'unpack', 'uphold',
            'upset', 'upstage', 'urge', 'untie', 'use', 'usurp', 'utter',
            'vacuum', 'value', 'vanish', 'vanquish', 'venture', 'visit',
            'voice', 'volunteer', 'vote', 'vouch', 'wail', 'wait', 'wake',
            'walk', 'wallow', 'wander', 'want', 'warm', 'warn', 'wash', 'waste',
            'watch', 'water', 'wave', 'waver', 'wear', 'weave', 'wed', 'weigh',
            'welcome', 'whimper', 'whine', 'whip', 'whirl', 'whisper',
            'whistle', 'win', 'wink', 'wipe', 'wish', 'wobble', 'wonder',
            'work', 'worry', 'wrap', 'wreck', 'wrestle', 'wriggle', 'write',
            'writhe', 'x-ray', 'yawn', 'yell', 'yelp', 'yield', 'yodel', 'zip',
            'zoom', ]

    adverb = ['abnormally', 'absentmindedly', 'accidentally', 'actually',
              'adventurously', 'afterwards', 'almost', 'always', 'annually',
              'anxiously', 'arrogantly', 'awkwardly', 'bashfully',
              'beautifully', 'bitterly', 'bleakly', 'blindly', 'blissfully',
              'boastfully', 'boldly', 'bravely', 'briefly', 'brightly',
              'briskly', 'broadly', 'busily', 'calmly', 'carefully',
              'carelessly', 'cautiously', 'certainly', 'cheerfully', 'clearly',
              'cleverly', 'closely', 'coaxingly', 'colorfully', 'commonly',
              'continually', 'coolly', 'correctly', 'courageously', 'crossly',
              'cruelly', 'curiously', 'daily', 'daintily', 'dearly',
              'deceivingly', 'deeply', 'defiantly', 'deliberately',
              'delightfully', 'diligently', 'dimly', 'doubtfully', 'dreamily',
              'easily', 'elegantly', 'energetically', 'enormously',
              'enthusiastically', 'equally', 'especially', 'even', 'evenly',
              'eventually', 'exactly', 'excitedly', 'extremely', 'fairly',
              'faithfully', 'famously', 'far', 'fast', 'fatally', 'ferociously',
              'fervently', 'fiercely', 'fondly', 'foolishly', 'fortunately',
              'frankly', 'frantically', 'freely', 'frenetically', 'frightfully',
              'fully', 'furiously', 'generally', 'generously', 'gently',
              'gladly', 'gleefully', 'gracefully', 'gratefully', 'greatly',
              'greedily', 'happily', 'hastily', 'healthily', 'heavily',
              'highly', 'honestly', 'hopelessly',
              'hourly', 'hungrily', 'immediately', 'innocently',
              'inquisitively', 'instantly', 'intensely', 'intently',
              'interestingly', 'inwardly', 'irritably', 'jaggedly', 'jealously',
              'jovially', 'joyfully', 'joyously', 'jubilantly', 'judgmentally',
              'justly', 'keenly', 'kiddingly', 'kindheartedly', 'kindly',
              'knavishly', 'knowingly', 'knowledgeably', 'kookily', 'lazily',
              'les', 'lightly', 'likely', 'limply', 'lively', 'loftily',
              'longingly', 'loosely', 'loudly', 'lovingly', 'loyally', 'madly',
              'majestically', 'meaningfully', 'mechanically', 'merrily',
              'miserably', 'mockingly', 'monthly', 'more', 'mortally', 'mostly',
              'mysteriously', 'naturally', 'hopelessly', 'hourly', 'hungrily',
              'immediately', 'innocently', 'inquisitively', 'instantly',
              'intensely', 'intently', 'interestingly', 'inwardly', 'irritably',
              'jaggedly', 'jealously', 'jovially', 'joyfully', 'joyously',
              'jubilantly', 'judgmentally', 'justly', 'keenly', 'kiddingly',
              'kindheartedly', 'kindly', 'knavishly', 'knowingly',
              'knowledgeably', 'kookily', 'lazily', 'less', 'lightly', 'likely',
              'limply', 'lively', 'loftily', 'longingly', 'loosely', 'loudly',
              'lovingly', 'loyally', 'madly', 'majestically', 'meaningfully',
              'mechanically', 'merrily', 'miserably', 'mockingly', 'monthly',
              'more', 'mortally', 'mostly', 'mysteriously', 'naturally',
              'nearly', 'neatly', 'nervously', 'never', 'nicely', 'noisily',
              'not', 'obediently', 'obnoxiously', 'oddly', 'offensively',
              'officially', 'often', 'only', 'openly', 'optimistically',
              'overconfidently', 'painfully', 'partially', 'patiently',
              'perfectly', 'physically', 'playfully', 'politely', 'poorly',
              'positively', 'potentially', 'powerfully', 'promptly', 'properly',
              'punctually', 'quaintly', 'queasily', 'queerly', 'questionably',
              'quicker', 'quickly', 'quietly', 'quirkily', 'quizzically',
              'randomly', 'rapidly', 'rarely', 'readily', 'really',
              'reassuringly', 'recklessly', 'regularly', 'reluctantly',
              'repeatedly', 'reproachfully', 'restfully', 'righteously',
              'rightfully', 'rigidly', 'roughly', 'rudely', 'safely',
              'scarcely', 'scarily', 'searchingly', 'sedately', 'seemingly',
              'seldom', 'selfishly', 'separately', 'seriously', 'shakily',
              'sharply', 'sheepishly', 'shrilly', 'shyly', 'silently',
              'sleepily', 'slowly', 'smoothly', 'softly', 'solemnly', 'solidly',
              'sometimes', 'soon', 'speedily', 'stealthily', 'sternly',
              'strictly', 'successfully', 'suddenly', 'supposedly',
              'surprisingly', 'suspiciously', 'sweetly', 'swiftly',
              'sympathetically', 'tenderly', 'tensely', 'terribly',
              'thankfully', 'thoroughly', 'thoughtfully', 'tightly', 'tomorrow',
              'too', 'tremendously', 'triumphantly', 'truly', 'truthfully',
              'rightfully', 'scarcely', 'searchingly', 'sedately', 'seemingly',
              'selfishly', 'separately', 'seriously', 'sheepishly', 'smoothly',
              'solemnly', 'sometimes', 'speedily', 'stealthily', 'successfully',
              'suddenly', 'supposedly', 'surprisingly', 'suspiciously',
              'sympathetically', 'tenderly', 'thankfully', 'thoroughly',
              'thoughtfully', 'tomorrow', 'tremendously', 'triumphantly',
              'truthfully', 'ultimately', 'unabashedly', 'unaccountably',
              'unbearably', 'unethically', 'unexpectedly', 'unfortunately',
              'unimpressively', 'unnaturally', 'unnecessarily', 'upbeat',
              'upright', 'upside down', 'upward', 'urgently', 'usefully',
              'uselessly', 'usually', 'utterly', 'vacantly', 'vaguely',
              'vainly', 'valiantly', 'vastly', 'verbally', 'very', 'viciously',
              'victoriously', 'violently', 'vivaciously', 'voluntarily',
              'warmly', 'weakly', 'wearily', 'well', 'wetly', 'wholly',
              'wildly', 'willfully', 'wisely', 'woefully', 'wonderfully',
              'worriedly', 'wrongly', 'yawningly', 'yearly', 'yearningly',
              'yesterday', 'yieldingly', 'youthfully', 'zealously', 'zestfully',
              'zestily']

    if grammar == 'noun' and word not in noun:
        return False
    elif grammar == 'adverb' and word not in adverb:
        return False
    elif grammar == 'adjective' and word not in adjective:
        return False
    elif grammar == 'verb' and word not in verb:
        return False
    else:
        return True

if __name__ == '__main__':
    app.run()
